name: custom_marker_builder
description: A Flutter package to create dynamic custom markers for Google Maps using Flutter widgets.
version: 0.0.1
homepage: https://github.com/tade-dev/custom_map_marker_builder
environment:
  sdk: '^3.6.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true