name: custom_marker_builder
description: A Flutter package to create dynamic custom markers for Google Maps using Flutter widgets.
version: 1.0.0
author: Akintade Oluwaseun <akintadeseun816@gmail.com>
homepage: https://github.com/tade-dev/custom_map_marker_builder
environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.custom_marker_builder
        pluginClass: CustomMarkerBuilderPlugin